# -*- coding: utf-8 -*-
"""(PA)Q2By praise Yakubu 20006951

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRvcFavUCkGnIyhcxk9Kd3BiVZrQVkwn
"""

# Display a welcome message
print("##########################")
print("WELCOME TO DBS CONSOLE")
print("##########################")

# Prompt the user for an input
user_input = input("Please enter your username:\n")

# If the input contains a backward slash '\'
if '\\' in user_input:
   # Split domain and username
   domain, username = user_input.split('\\', 1)

   # Display data and individual items
   #print("\n{}".format(user_input))
   print("\nDomain: {}".format(domain))
   print("Username: {}".format(username))
else:
   print("\nInvalid format. Please use the format 'Domain\\Username'.")
   print("Example: DBS\\7417722")